import {
    BadgeCheck,
    Bell,
    Boxes,
    Building,
    Calculator,
    Car,
    ChartColumn,
    ChartLine,
    ChefHat,
    ClipboardList,
    Clock,
    Cloud,
    Coffee,
    CreditCard,
    FileText,
    Gift,
    Globe,
    HandCoins,
    Headphones,
    Heart,
    Landmark,
    Lock,
    MessageCircle,
    Monitor,
    Package,
    Percent,
    Pill,
    Printer,
    QrCode,
    Receipt,
    RefreshCw,
    Scissors,
    ShieldCheck,
    Shirt,
    ShoppingBasket,
    Smartphone,
    Sparkles,
    Star,
    Store,
    Tag,
    Truck,
    Users,
    UtensilsCrossed,
    Wallet,
    Warehouse,
    WashingMachine,
    WifiOff,
    Zap,
    type LucideIcon,
} from 'lucide-react';

/**
 * Ikon blok situs pemasaran (konsol memilih nama dari `SkemaBagianSitus::IKON`). Memakai ikon garis lucide yang
 * sama dengan back-office (D-39): sebelumnya ikon raster navigasi yang dipetakan seadanya ("WifiOff" tampil sebagai
 * gambar Retur), kecil dan buram di layar retina. Diimpor satu per satu supaya bundle situs hanya membawa ikon ini.
 */
export const DaftarIkonSitus: Record<string, LucideIcon> = {
    WifiOff,
    Receipt,
    Package,
    ChartColumn,
    Users,
    Store,
    Coffee,
    Scissors,
    Shirt,
    Truck,
    ShieldCheck,
    Smartphone,
    Printer,
    Tag,
    Gift,
    Wallet,
    Calculator,
    Clock,
    Cloud,
    Headphones,
    Zap,
    BadgeCheck,
    QrCode,
    UtensilsCrossed,
    ShoppingBasket,
    Building,
    ChartLine,
    Percent,
    Star,
    Heart,
    Sparkles,
    Monitor,
    CreditCard,
    Boxes,
    ClipboardList,
    WashingMachine,
    Warehouse,
    Globe,
    Lock,
    RefreshCw,
    MessageCircle,
    Bell,
    FileText,
    Landmark,
    HandCoins,
    ChefHat,
    Pill,
    Car,
};

export default function IkonSitus({ nama, className }: { nama: string | null; className?: string }) {
    const Ikon = nama ? DaftarIkonSitus[nama] : undefined;

    return Ikon ? <Ikon aria-hidden="true" strokeWidth={1.75} className={className ?? 'size-6'} /> : null;
}
